baseurl: "https://docs.StrawberrySSG.com/"
title: "Strawberry Docs"
theme: gothamhq-2020

googleAnalytics: ""

enableEmoji: true

params:
  description: "Documentation for the Strawberry static site generator."

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: "Using Strawberry"
      url: "/gotham/"
      weight: 5
    - name: "Strawberry Dev"
      url: "/development/"
      weight: 10
    #- name: "Reference"
    #  weight: 15
    - name: "Back to HQ"
      url: "https://www.StrawberrySSG.com"
      weight: 20
  gotham:
    - name: "Quickstart"
      identifier: quickstart
      weight: 5
    - name: "Manual"
      identifier: manual
      weight: 10
